# -*- coding: utf-8 -*-
"""test_data_recipie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12sc3WGKW6ykhU39tDqyCiP6INlcG8vip
"""

import pandas as pd

df = pd.read_csv("hf://datasets/AkashPS11/recipes_data_food.com/recipes.csv")

print(df.columns)

df



display(df['Images'])

# Filter the DataFrame to include only rows where 'extracted_image_urls' is not empty
recipes_with_images_df = df[df['extracted_image_urls'].apply(lambda x: len(x) > 0)]

# Display the filtered DataFrame
display(recipes_with_images_df)

# Count the number of recipes with extracted image URLs
# A recipe has extracted image URLs if the list in the 'extracted_image_urls' column is not empty.
recipes_with_images_count = df[df['extracted_image_urls'].apply(lambda x: len(x) > 0)].shape[0]

print(f"Number of recipes with extracted image URLs: {recipes_with_images_count}")

import re

def extract_urls(image_string):
    if pd.isna(image_string):
        return []
    # Use regex to find content within c(...) and then find URLs
    match = re.search(r'c\((.*)\)', image_string)
    if match:
        content = match.group(1)
        # Find all strings that look like URLs within the content
        urls = re.findall(r'"(https?://[^"]+)"', content)
        return urls
    return []

# Apply the function to the 'Images' column to extract URLs
df['extracted_image_urls'] = df['Images'].apply(extract_urls)

# Display the original 'Images' column and the new column with extracted URLs
display(df[['Images', 'extracted_image_urls']].head())



import re

def extract_ingredients(ingredient_string):
    if pd.isna(ingredient_string):
        return []
    # Use regex to find content within c(...)
    match = re.search(r'c\((.*)\)', ingredient_string)
    if match:
        content = match.group(1)
        # Find all strings within double quotes
        ingredients = re.findall(r'"([^"]+)"', content)
        return ingredients
    return []

# Apply the function to the 'RecipeIngredientParts' column
recipes_with_images_df['extracted_ingredients'] = recipes_with_images_df['RecipeIngredientParts'].apply(extract_ingredients)

# Display the original 'RecipeIngredientParts' column and the new column with extracted ingredients
display(recipes_with_images_df[['RecipeIngredientParts', 'extracted_ingredients']].head())

display(recipes_with_images_df['Calories'])

display(recipes_with_images_df)



display(recipes_with_images_df['RecipeCategory'].unique())

# Display the first few rows of the relevant columns
display(recipes_with_images_df[['RecipeCategory', 'extracted_ingredients']].head())

# Check for missing values in the specified columns
missing_recipe_category = recipes_with_images_df['RecipeCategory'].isnull().sum()
missing_extracted_ingredients = recipes_with_images_df['extracted_ingredients'].isnull().sum()

print(f"Missing values in 'RecipeCategory': {missing_recipe_category}")
print(f"Missing values in 'extracted_ingredients': {missing_extracted_ingredients}")
